### ISSUE TITLE
Design and prepare mockups of the part of the front end

### ISSUE THREAD

**Issue by kpagacz** [kpagacz/wiki-on-fire#1]
Design a color scheme and basic layouts for:
- Main page
- User Page
- Search Page

**Comment by kpagacz** [comment]
FIGMA board; https://www.figma.com/file/7s6au8x81kMz1EvimT8PTF/Team-project-Layouts?node-id=0%3A1

**Comment by kpagacz** [comment]
I am happy to close this for now and create more design tasks when the need arises.

Are you happy with closing?

**Comment by karolkozlo** [comment]
Done. More design tasks will be added later.
