### ISSUE TITLE
Add a flowchart with the /login endpoint to the miro mockups.

### ISSUE THREAD

**Issue by kpagacz** [kpagacz/wiki-on-fire#117]
There's already one about registration, so treat is as a point of reference.

**Comment by karolkozlo** [comment]
Figma mockups? It should not be "Miro mockups"?

**Comment by kpagacz** [comment]
Miro, definitely Miro.

**Comment by kpagacz** [comment]
https://miro.com/app/board/o9J_lrS-SJ0=/

**Comment by kpagacz** [comment]
![image](https://user-images.githubusercontent.com/24480246/143928637-0c4ef87a-321f-416e-af14-790a83671112.png)

Let me know what you think @karolkozlo

**Comment by karolkozlo** [comment]
Looks good for me

**Comment by kpagacz** [comment]
Closing then.
