### ISSUE TITLE
Add logout button to header

### ISSUE THREAD

**Issue by karolkozlo** [kpagacz/wiki-on-fire#120]
When user is logged in, we should display logout button in Header.
Should be displayed conditionally.
Design based on Figma (User Page header)

We should update icon set via Fontello to use leave-icon on button.

**Comment by hritikb27** [comment]
Hey guys I'm a beginner MERN stack developer and I'm searching for opportunities to work with some more experienced developers on their project like you guys. Is there a possibility that I can communicate with you and contribute to this repo?
