### ISSUE TITLE
Create AutoLogin endpoint

### ISSUE THREAD

**Issue by karolkozlo** [kpagacz/wiki-on-fire#141]
Endpoint will receive cookie with token and should return logged user data.

**Comment by kpagacz** [comment]
This could actually route towards the getUser controller with the username provided from the token. I currently don't have the concrete implementation in mind but it should be feasible to do it quite elegantly.

I am also unsure whether this would require any changes to the output of the getUsers controller.

**Comment by kpagacz** [comment]
This task also includes making changes to spotlight.
