### ISSUE TITLE
Prepare report

### ISSUE THREAD

**Issue by karolkozlo** [kpagacz/wiki-on-fire#155]
We need to prepare a report and send it by 21 December.
We should send:
 - Screenshot of our Backlog
 - Product register document (see ~mak/info)
 - Sprint register (see ~mak/info)

**Comment by mwiech99** [comment]
Link to the report: https://drive.google.com/drive/folders/1JJJ_--1hI-NgwV5F9VnLCtDCXeIHR-UP?usp=sharing
