### ISSUE TITLE
Create http layer for pagination

### ISSUE THREAD

**Issue by karolkozlo** [kpagacz/wiki-on-fire#180]
Function that will return number of pages. It will be used to display proper number of page links #174 
~~Arguments: number of articles we need to get in one call.~~

Konrad EDIT: argument: number of articles per page

**Comment by kpagacz** [comment]
I also don't think this is so simple. First of all, the frontend application won't request simply the number of articles from the articles endpoint. From what I have seen from https://github.com/kpagacz/wiki-on-fire/issues/179 we want to summarize data from multiple backend endpoints, parametrized by some time frames. So a single number of articles per page argument is definitely not enough. It also seems like such parameters as number of articles per page should be passed to the function created in here: https://github.com/kpagacz/wiki-on-fire/issues/179

**Comment by kpagacz** [comment]
I am closing this in favour of the modified scope of #179.
