### ISSUE TITLE
Design the database schema

### ISSUE THREAD

**Issue by kpagacz** [kpagacz/wiki-on-fire#4]

**Comment by mwiech99** [comment]
Current database schema: 
[schema_v3.pdf](https://github.com/kpagacz/wiki-on-fire/files/7449077/schema_v3.pdf)

**Comment by mwiech99** [comment]
update
[schema_v4.pdf](https://github.com/kpagacz/wiki-on-fire/files/7512597/schema_v4.pdf)

**Comment by kpagacz** [comment]
Ok, this is good enough, can I ask you to put on a Google Drive, create a read only link and put in the main README file, @mwiech99 ?
