### ISSUE TITLE
size prop of WofIcon does not seem to have an effect on the size of the icon

### ISSUE THREAD

**Issue by kpagacz** [kpagacz/wiki-on-fire#76]
@karolkozlo have a look
![image](https://user-images.githubusercontent.com/24480246/141376390-a5e0fefe-f2a2-4482-b6e2-e676bc26c6b0.png)

Changing the font-size does not seem to change the size of the icon.
Code to reproduce: 
1. Paste into the template of app.vue after importing the WofIcon component
```js
<wof-icon class="wof-like" size=20 />
```
2. Serve the frontend and play with the css - the icon has the same size no matter the font-size attribute of the element.

**Comment by karolkozlo** [comment]
<wof-icon icon="wof-like" :size="50" />
It's should work. Try it.

**Comment by kpagacz** [comment]
I got it to work. Seems I misunderstood how to pass Number atomics to components (needs : to force evaluation of the expression)
